# Site settings
title: 30dienu.lt
header-img: img/home-bg.jpg
email: dainiuxt@gmail.com
description: "30 dienų gali pakeisti tavo gyvenimą. Pradėk keistis jau šiandien!"
baseurl: "/30dienu-clean"
url: "https://github.com/dainiuxt"
twitter_username: 
github_username:  
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
